### ISSUE TITLE
Content-Security-Policy : nonce not added in datepicker and autocompleter

### ISSUE THREAD

**Issue by vpkg** [struts-community-plugins/struts2-jquery#435]
Hello,
I have the latest versions : struts2-jquery-plugin v5.0.3 and struts2 v6.1.2.2.

The nonce is generated in the http header by a custom CspInterceptor / CspSettings in struts2
```
Content-Security-Policy: style-src 'self' 'unsafe-inline'; script-src 'self' https://www.google.com/ https://www.gstatic.com/' 'nonce-LxRB8yZYkUFNMvVIPLJL5WTl'
``` 

Then it works most of the time
```html
<script type="text/javascript" src="/myApp/static/js/base/jquery-3.7.0.js" nonce="LxRB8yZYkUFNMvVIPLJL5WTl">
</script>
<script type="text/javascript" src="/myApp/static/js/plugins/jquery.subscribe.js?s2j=5.0.3" nonce="LxRB8yZYkUFNMvVIPLJL5WTl">
</script>
<script type="text/javascript" src="/myApp/static/js/struts2/jquery.struts2.js?s2j=5.0.3" nonce="LxRB8yZYkUFNMvVIPLJL5WTl">
</script>

<script type="text/javascript" nonce="LxRB8yZYkUFNMvVIPLJL5WTl">
    $(function () {
        jQuery.struts2_jquery.version = "5.0.3";
        jQuery.scriptPath = "/myApp/static/";
        jQuery.struts2_jquery.minSuffix = "";
        jQuery.struts2_jquery.local = "fr";
        jQuery.struts2_jquery.gridLocal = "fr";
        jQuery.struts2_jquery.timeLocal = "fr";
        jQuery.struts2_jquery.datatablesLocal = "fr";
        jQuery.ajaxSettings.traditional = true;

        jQuery.ajaxSetup({
            cache: false
        });


    });
</script>
``` 

But not for the datepicker or autocompleter, and probably others.
Original jsp code :
```html
<sj:datepicker name="criteria.startDate" label="default" buttonImageOnly="true" displayFormat="dd/mm/yy" changeYear="true" />
``` 

Generated html code :
```html
<input type="text" name="criteria.startDate" value="" id="datepicker_688640944"/></td>
<script type='text/javascript'>
jQuery(document).ready(function () {
	jQuery.struts2_jquery_ui.initDatepicker(false);

});
jQuery(document).ready(function () {
	var options_datepicker_688640944 = {};
	options_datepicker_688640944.autoSize = true;
	options_datepicker_688640944.constrainInput = false;
	options_datepicker_688640944.buttonImageOnly = true;
	options_datepicker_688640944.changeYear = true;
	options_datepicker_688640944.showOn = "both";
	options_datepicker_688640944.buttonImage = "/myApp/struts/js/calendar.gif";
	options_datepicker_688640944.displayformat = "dd/mm/yy";
	options_datepicker_688640944.jqueryaction = "datepicker";
	options_datepicker_688640944.id = "datepicker_688640944";
	options_datepicker_688640944.name = "criteria.startDate";

jQuery.struts2_jquery_ui.bind(jQuery('#datepicker_688640944'),options_datepicker_688640944);
 });
</script>
``` 

Error on the browser :
```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https://www.google.com/ https://www.gstatic.com/' 'nonce-LxRB8yZYkUFNMvVIPLJL5WTl'". Either the 'unsafe-inline' keyword, a hash ('sha256-TyiU9UoXEXp1wcUNE++ldb6YD5TOW0zTmQV0G5JARbM='), or a nonce ('nonce-...') is required to enable inline execution.
``` 

The nonce attribute is missing. When I take a look at datepicker-close.ftl there's
```html
<@s.script type='text/javascript'>
jQuery(document).ready(function () {
  <#if parameters.timepicker!false>
	jQuery.struts2_jquery_ui.initDatepicker(true);
  <#else>
	jQuery.struts2_jquery_ui.initDatepicker(false);
  </#if>

});
``` 

So I guess the <@s.script type='text/javascript'> should have returned <script  type="text/javascript" nonce="xxx"> like the others but it's not the case.

**Comment by gregh3269** [comment]
It works in the showcase.  On your page what tags are you including?

**Comment by vpkg** [comment]
I have only the standard tags
```html
<%@ taglib prefix="s" uri="/struts-tags"%>
<%@ taglib prefix="sj" uri="/struts-jquery-tags"%>
```

**Comment by lukaszlenart** [comment]
I think this is fixed but not released yet. There is still one blocking issue but maybe we should postpone fixing it and cut a release.

**Comment by vpkg** [comment]
@gregh3269 , you are right, it works in the showcase (datepicker.jsp) of the 5.0.3 version. I can't figure out what is different in my code. Tried to simplify my jsp, switched to the standard struts2 CSP (even with report-only) but still doesn't work.

@lukaszlenart , I'm eagerly waiting for your fix if you think it may solve my problem !

**Comment by gregh3269** [comment]
Maybe its missing the <sj:head jqueryui="true" /> I can see from the source that there is a check on the nonce.

**Comment by vpkg** [comment]
I had put <sj:head jqueryui="false" /> for test purpose but with <sj:head jqueryui="true" />, it doesn't work better.
I even took the datepicker.jsp in my app :
```html
<%@ taglib prefix="s" uri="/struts-tags" %>
<%@ taglib prefix="sj" uri="/struts-jquery-tags" %>

<head>
<sj:head jqueryui="true" />
</head>
<body>
<h1>Struts test</h1>

<h2>Datepicker</h2>

<p class="text">
	A simple Datepicker
</p>
<s:form id="form" theme="xhtml">
	<sj:datepicker id="date0" name="date0" maxDate="-1d" label="Select a Date"/>
	<sj:datepicker id="date1" name="date1" value="%{dateValue}" label="Date Value from Action"/>
	<sj:datepicker id="date2" name="nameValue" label="Date Value by Name"/>
	<sj:datepicker id="date3" name="date3" value="today" displayFormat="dd.mm.yy" label="Today"/>
	<sj:datepicker id="date4" name="date4" value="yesterday" displayFormat="mm/dd/yy" label="Yesterday"/>
	<sj:datepicker id="date5" name="date5" value="tomorrow" displayFormat="DD, d MM yy" label="Tomorrow"/>
	<sj:datepicker id="date6" name="date6" value="2004-08-14" displayFormat="d M, yy" label="String Value"/>
	<sj:datepicker id="date7" name="date7" value="today" displayFormat="d M, yy" minDate="minValue" maxDate="maxValue"
	               label="With min and max Date"/>
</s:form>
``` 

And still no nonce in <script> for the date picker
```html
<head>

<script type="text/javascript" src="/myApp/static/js/base/jquery-3.7.0.min.js" nonce="HHT5lXob8OsVIVolHewDEMwq">
</script>
        <!-- script type="text/javascript" src="/myApp/static/js/base/core.min.js?s2j=5.0.3"></script -->
<script type="text/javascript" src="/myApp/static/js/base/version.min.js" nonce="HHT5lXob8OsVIVolHewDEMwq">
</script>
<script type="text/javascript" src="/myApp/static/js/plugins/jquery.subscribe.min.js?s2j=5.0.3" nonce="HHT5lXob8OsVIVolHewDEMwq">
</script>

<script type="text/javascript" src="/myApp/static/js/struts2/jquery.struts2.min.js?s2j=5.0.3" nonce="HHT5lXob8OsVIVolHewDEMwq">
</script>

<script type="text/javascript" nonce="HHT5lXob8OsVIVolHewDEMwq">
    $(function () {
        jQuery.struts2_jquery.version = "5.0.3";
        jQuery.scriptPath = "/myApp/static/";
        jQuery.ajaxSettings.traditional = true;

        jQuery.ajaxSetup({
            cache: false
        });

        jQuery.struts2_jquery.require("js/struts2/jquery.ui.struts2.min.js?s2j=5.0.3");

    });
</script>

<link rel="stylesheet" type="text/css" href="/myApp/static/themes/smoothness/jquery-ui.css?s2j=5.0.3" nonce="HHT5lXob8OsVIVolHewDEMwq"/>

</head>
<body>
<h1>Struts test</h1>

<h2>Datepicker</h2>

<p class="text">
	A simple Datepicker
</p>
<form id="form" name="form" action="/myApp/TestStruts.do" method="post" class="form-inline">
	<label for="date0">Select a Date</label><input type="text" name="date0" value="" id="date0"/><script type='text/javascript'>
jQuery(document).ready(function () {
	jQuery.struts2_jquery_ui.initDatepicker(false);

});
jQuery(document).ready(function () {
	var options_date0 = {};
	options_date0.autoSize = true;
	options_date0.constrainInput = false;
	options_date0.showOn = "both";
	options_date0.buttonImage = "/myApp/struts/js/calendar.gif";
	options_date0.maxDate = "-1d";
	options_date0.jqueryaction = "datepicker";
	options_date0.id = "date0";
	options_date0.name = "date0";

jQuery.struts2_jquery_ui.bind(jQuery('#date0'),options_date0);
 });
</script>
```

**Comment by gregh3269** [comment]
In the struts2-bootstrap-showcase plugin there is a page with the date picker and autocomplete that works, and is possibly simpler to use as a comparison than the struts2-jquery-showcase.

struts2-bootstrap-showcase/src/main/webapp/WEB-INF/content/jquery.jsp

One difference I can see from above is it includes <sb:head includeScripts="true"/>

**Comment by lukaszlenart** [comment]
@vpkg could you try to use the SNAPSHOT version?

**Comment by vpkg** [comment]
Sorry for delay, I had urgent staff to finish.
I took version 5.0.4-SNAPSHOT and datepicker.jsp from the showcase into my project but it still doesn't work.

The sample jsp (with or without `<sj:head>`, also true/false with `jqueryui` and `jquery` attributes (`includeScripts` doesn't exist)
```html
<%@ taglib prefix="s" uri="/struts-tags" %>
<%@ taglib prefix="sj" uri="/struts-jquery-tags" %>

<head>
<sj:head jqueryui="true" jquery="true" />
</head>
<body>
<h2>Datepicker</h2>

<p class="text">
	A simple Datepicker
</p>
<s:form id="form" theme="xhtml">
	<sj:datepicker id="date0" name="date0" maxDate="-1d" label="Select a Date"/>
``` 

Generated html, still `<script type='text/javascript'>` for the datepicker
```html
<head>

<script type="text/javascript" src="/myApp/static/js/base/jquery-3.7.1.min.js" nonce="wEODlrLJXindS1V-S1iQuzGr">
</script>
        <!-- script type="text/javascript" src="/myApp/static/js/base/core.min.js?s2j=5.0.4-SNAPSHOT"></script -->
<script type="text/javascript" src="/myApp/static/js/base/version.min.js" nonce="wEODlrLJXindS1V-S1iQuzGr">
</script>
<script type="text/javascript" src="/myApp/static/js/plugins/jquery.subscribe.min.js?s2j=5.0.4-SNAPSHOT" nonce="wEODlrLJXindS1V-S1iQuzGr">
</script>

<script type="text/javascript" src="/myApp/static/js/struts2/jquery.struts2.min.js?s2j=5.0.4-SNAPSHOT" nonce="wEODlrLJXindS1V-S1iQuzGr">
</script>

<script type="text/javascript" nonce="wEODlrLJXindS1V-S1iQuzGr">
    $(function () {
        jQuery.struts2_jquery.version = "5.0.4-SNAPSHOT";
        jQuery.scriptPath = "/myApp/static/";
        jQuery.ajaxSettings.traditional = true;

        jQuery.ajaxSetup({
            cache: false
        });

        jQuery.struts2_jquery.require("js/struts2/jquery.ui.struts2.min.js?s2j=5.0.4-SNAPSHOT");

    });
</script>

<link rel="stylesheet" type="text/css" href="/myApp/static/themes/smoothness/jquery-ui.css?s2j=5.0.4-SNAPSHOT" nonce="wEODlrLJXindS1V-S1iQuzGr"/>

</head>
<body>
<h2>Datepicker</h2>

<p class="text">
	A simple Datepicker
</p>
<form id="form" name="form" action="/myApp/TestStruts.do" method="post" class="form-inline">
	<label for="date0">Select a Date</label><input type="text" name="date0" value="" id="date0"/>
<script type='text/javascript'>
jQuery(document).ready(function () {
	jQuery.struts2_jquery_ui.initDatepicker(false);

});
jQuery(document).ready(function () {
	var options_date0 = {};
	options_date0.autoSize = true;
	options_date0.constrainInput = false;
	options_date0.showOn = "both";
	options_date0.buttonImage = "/myApp/struts/js/calendar.gif";
	options_date0.maxDate = "-1d";
	options_date0.jqueryaction = "datepicker";
	options_date0.id = "date0";
	options_date0.name = "date0";

jQuery.struts2_jquery_ui.bind(jQuery('#date0'),options_date0);
 });
</script>

	<label for="date1">Date Value from Action</label><input type="text" name="date1" value="" id="date1"/><script type='text/javascript'>
jQuery(document).ready(function () {
	jQuery.struts2_jquery_ui.initDatepicker(false);

});
jQuery(document).ready(function () {
	var options_date1 = {};
	options_date1.autoSize = true;
	options_date1.constrainInput = false;
	options_date1.showOn = "both";
	options_date1.buttonImage = "/myApp/struts/js/calendar.gif";
	options_date1.jqueryaction = "datepicker";
	options_date1.id = "date1";
	options_date1.name = "date1";

jQuery.struts2_jquery_ui.bind(jQuery('#date1'),options_date1);
 });
</script>
```

**Comment by vpkg** [comment]
@gregh3269 and @lukaszlenart , at last I understood why the nonce was not generated in the script tag.
The problem was in our framework that redefines autocompleter.ftl / autocompleter-close.ftl and datepicker.ftl / datepicker-close.ftl.
Even if the standard `<sj:datepicker>` tag was used in the jsp, the ftl was taken from our framework and not from struts-jquery-tags (I could see that when running struts2 in debug mode).

When I realized that (I didn't know it could even exist), I just had to change `<script type='text/javascript'>` by `<@s.script type='text/javascript'>` in our framework ftl and it worked !

**Comment by lukaszlenart** [comment]
Great to hear that :) You can read more about templates overriding here
https://struts.apache.org/tag-developers/template-loading#overriding-templates
https://struts.apache.org/tag-developers/extending-themes

**Comment by vpkg** [comment]
FYI, I had this issue with jQuery after fixing the ftl in our framework
https://github.com/jquery/jquery/issues/5374
I proposed a fix / workaround.

Edit : not a bug from struts2-jquery neither from jquery, but from my CSP. Workaround not valid.
